name: Terraform Plan Summary

on:
  push

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Run terraform plan
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::409598018072:role/emmaliaocode-githubaction-role

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
           terraform_version: "^1.10.2"
           terraform_wrapper: false

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Terraform Plan
        run: |
          terraform init
          terraform plan -var-file=env/ap-northeast-1.tfvars -out=terraform_plan_output.txt

      - name: Print Terraform Plan Summary
        uses: sgametrio/terraform-summary-action@main
        with:
          log-file: terraform_plan_output.txt
